package com.chail.jdbcutilsone;

public class TestJdbc {

	@org.junit.Test
	public void testOracle9i() throws Exception {
		String user = "chail";
		String pass = "chail";
		String url = "jdbc:oracle:thin:@192.168.210.80:1521/ora9i";
		JDBCUtil jdbcUtil = new JDBCUtil(url, JdbcDirver.ORACLE_DRIVER, user, pass);
		jdbcUtil.getConnection();
		String sql = "SELECT ALL_TAB_COLUMNS.OWNER,ALL_TAB_COLUMNS.TABLE_NAME,ALL_TAB_COLUMNS.COLUMN_NAME,ALL_TAB_COLUMNS.DATA_TYPE,ALL_TAB_COLUMNS.CHAR_LENGTH,ALL_TAB_COLUMNS.NULLABLE,ALL_TAB_COLUMNS.DATA_PRECISION,ALL_TAB_COLUMNS.DATA_SCALE,ALL_TAB_COLUMNS.DATA_LENGTH,ALL_TAB_COLUMNS.CHAR_USED,ALL_TAB_COLUMNS.COLUMN_ID,ALL_COL_COMMENTS.COMMENTS,ALL_TAB_COLUMNS.DATA_DEFAULT,ALL_TAB_COLUMNS.DEFAULT_LENGTH,ALL_TAB_COLUMNS.DATA_TYPE_MOD,ALL_TAB_COLUMNS.DATA_TYPE_OWNER FROM ALL_TAB_COLUMNS, ALL_COL_COMMENTS WHERE ALL_TAB_COLUMNS.OWNER = ALL_COL_COMMENTS.OWNER AND ALL_TAB_COLUMNS.TABLE_NAME = ALL_COL_COMMENTS.TABLE_NAME AND ALL_TAB_COLUMNS.COLUMN_NAME=ALL_COL_COMMENTS.COLUMN_NAME AND ALL_TAB_COLUMNS.OWNER NOT IN ('SYSTEM','SYS','OUTLN','DIP','ORACLE_OCM','DBSNMP','APPQOSSYS','WMSYS','EXFSYS','CTXSYS','XDB','ANONYMOUS','XS$NULL','ORDSYS','ORDDATA','ORDPLUGINS','SI_INFORMTN_SCHEMA','MDSYS','OLAPSYS','MDDATA','SPATIAL_WFS_ADMIN_USR','SPATIAL_CSW_ADMIN_USR','SYSMAN','MGMT_VIEW','APEX_030200','FLOWS_FILES','APEX_PUBLIC_USER','OWBSYS','OWBSYS_AUDIT') AND NOT EXISTS (SELECT *  FROM ALL_VIEWS WHERE OWNER = ALL_TAB_COLUMNS.OWNER AND VIEW_NAME = ALL_TAB_COLUMNS.TABLE_NAME) ORDER BY 1, 2, 11";
		jdbcUtil.executeQuery(sql);
		jdbcUtil.releaseConnectn();
	}

}
